const products = [
  {
    id: Math.floor(Math.random() * 10000 + "astw4c"),
    name: "Rom Hoodie",
    description: "100% woolen rapture on my mind hoodile with cape.",
    ratings: 3,
    price: "100:00",
    imagePath: require("../../../Assets/blank-black-male-hoodie-sweatshirt-long-sleeve-with-clipping-path-png 2 (1).png"),
  },

  {
    id: Math.floor(Math.random() * 10000 + "astw4d"),
    name: "Rom Hoodie",
    description: "100% woolen rapture on my mind hoodile with cape.",
    ratings: 3,
    price: "100:00",
    imagePath: require("../../../Assets/blank-black-male-hoodie-sweatshirt-long-sleeve-with-clipping-path-png 2 (2).png"),
  },
  {
    id: Math.floor(Math.random() * 10000 + "astwcc"),
    name: "Rom Hoodie",
    description: "100% woolen rapture on my mind hoodile with cape.",
    ratings: 3,
    price: "100:00",
    imagePath: require("../../../Assets/blank-black-male-hoodie-sweatshirt-long-sleeve-with-clipping-path-png 2 (3).png"),
  },
  {
    id: Math.floor(Math.random() * 10000 + "astw4dccvv"),
    name: "Rom Hoodie",
    description: "100% woolen rapture on my mind hoodile with cape.",
    ratings: 3,
    price: "100:00",
    imagePath: require("../../../Assets/blank-black-male-hoodie-sweatshirt-long-sleeve-with-clipping-path-png 2 (4).png"),
  },
  {
    id: Math.floor(Math.random() * 10000 + "astw4dvcdd"),
    name: "Rom Hoodie",
    description: "100% woolen rapture on my mind hoodile with cape.",
    ratings: 3,
    price: "100:00",
    imagePath: require("../../../Assets/blank-black-male-hoodie-sweatshirt-long-sleeve-with-clipping-path-png 2 (5).png"),
  },
  {
    id: Math.floor(Math.random() * 10000 + "astw4dcpsw"),
    name: "Rom Hoodie",
    description: "100% woolen rapture on my mind hoodile with cape.",
    ratings: 3,
    price: "100:00",
    imagePath: require("../../../Assets/blank-black-male-hoodie-sweatshirt-long-sleeve-with-clipping-path-png 2.png"),
  },
  {
    id: Math.floor(Math.random() * 10000 + "astw4detwgss"),
    name: "Rom Hoodie",
    description: "100% woolen rapture on my mind hoodile with cape.",
    ratings: 3,
    price: "100:00",
    imagePath: require("../../../Assets/blank-black-male-hoodie-sweatshirt-long-sleeve-with-clipping-path-png 2 (4).png"),
  },
  {
    id: Math.floor(Math.random() * 10000 + "astw4dccwere"),
    name: "Rom Hoodie",
    description: "100% woolen rapture on my mind hoodile with cape.",
    ratings: 3,
    price: "100:00",
    imagePath: require("../../../Assets/blank-black-male-hoodie-sweatshirt-long-sleeve-with-clipping-path-png 2 (5).png"),
  },
  {
    id: Math.floor(Math.random() * 10000 + "astw4dxwrwr"),
    name: "Rom Hoodie",
    description: "100% woolen rapture on my mind hoodile with cape.",
    ratings: 3,
    price: "100:00",
    imagePath: require("../../../Assets/blank-black-male-hoodie-sweatshirt-long-sleeve-with-clipping-path-png 2.png"),
  },
  {
    id: Math.floor(Math.random() * 10000 + "astw4dxpqrtq"),
    name: "Rom Hoodie",
    description: "100% woolen rapture on my mind hoodile with cape.",
    ratings: 3,
    price: "100:00",
    imagePath: require("../../../Assets/blank-black-male-hoodie-sweatshirt-long-sleeve-with-clipping-path-png 2 (1).png"),
  },

  {
    id: Math.floor(Math.random() * 10000 + "astw4dcw2454"),
    name: "Rom Hoodie",
    description: "100% woolen rapture on my mind hoodile with cape.",
    ratings: 3,
    price: "100:00",
    imagePath: require("../../../Assets/blank-black-male-hoodie-sweatshirt-long-sleeve-with-clipping-path-png 2 (2).png"),
  },
  {
    id: Math.floor(Math.random() * 10000 + "astw4zvzwsfsfd"),
    name: "Rom Hoodie",
    description: "100% woolen rapture on my mind hoodile with cape.",
    ratings: 3,
    price: "100:00",
    imagePath: require("../../../Assets/blank-black-male-hoodie-sweatshirt-long-sleeve-with-clipping-path-png 2 (3).png"),
  },
  {
    id: Math.floor(Math.random() * 10000 + "astw4xxcxcd"),
    name: "Rom Hoodie",
    description: "100% woolen rapture on my mind hoodile with cape.",
    ratings: 3,
    price: "100:00",
    imagePath: require("../../../Assets/blank-black-male-hoodie-sweatshirt-long-sleeve-with-clipping-path-png 2 (1).png"),
  },

  {
    id: Math.floor(Math.random() * 10000 + "astwxswrrwtg4d"),
    name: "Rom Hoodie",
    description: "100% woolen rapture on my mind hoodile with cape.",
    ratings: 3,
    price: "100:00",
    imagePath: require("../../../Assets/blank-black-male-hoodie-sweatshirt-long-sleeve-with-clipping-path-png 2 (2).png"),
  },
  {
    id: Math.floor(Math.random() * 10000 + "ccsdastw4d"),
    name: "Rom Hoodie",
    description: "100% woolen rapture on my mind hoodile with cape.",
    ratings: 3,
    price: "100:00",
    imagePath: require("../../../Assets/blank-black-male-hoodie-sweatshirt-long-sleeve-with-clipping-path-png 2 (3).png"),
  },
  {
    id: Math.floor(Math.random() * 10000 + "astw4xxcsfsf"),
    name: "Rom Hoodie",
    description: "100% woolen rapture on my mind hoodile with cape.",
    ratings: 3,
    price: "100:00",
    imagePath: require("../../../Assets/blank-black-male-hoodie-sweatshirt-long-sleeve-with-clipping-path-png 2 (1).png"),
  },

  {
    id: Math.floor(Math.random() * 10000 + "astw4dzzqaa"),
    name: "Rom Hoodie",
    description: "100% woolen rapture on my mind hoodile with cape.",
    ratings: 3,
    price: "100:00",
    imagePath: require("../../../Assets/blank-black-male-hoodie-sweatshirt-long-sleeve-with-clipping-path-png 2 (2).png"),
  },
  {
    id: Math.floor(Math.random() * 10000 + "astw4dvzafqrqtq"),
    name: "Rom Hoodie",
    description: "100% woolen rapture on my mind hoodile with cape.",
    ratings: 3,
    price: "100:00",
    imagePath: require("../../../Assets/blank-black-male-hoodie-sweatshirt-long-sleeve-with-clipping-path-png 2 (3).png"),
  },
];

export default products;
